name: ges2024
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  data_table_2: ^2.5.8
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  dropdown_search: ^5.0.6
  excel: ^2.1.0
  expandable_datatable: ^0.0.7
  expansion_tile_card: ^3.0.0
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^15.1.1
  flutter_widget_from_html: ^0.10.4
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: null
  horizontal_data_table: ^4.3.1
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  pin_code_fields: ^8.0.1
  pinch_zoom: ^1.0.0
  quill_html_editor: ^2.2.6
  shimmer: ^3.0.0
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
