on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v2
  with:
    distribution: 'zulu'
    java-version: '11'
- uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.7.7'
- run: flutter pub get
- run: flutter test
- run: flutter build apk
- run: flutter build appbundle

      - name: Push to Releases
        uses: subosito/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}
